server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  server:
    #关闭自我保护机制
    enable-self-preservation: false
    #删除过期服务的事件间隔
#    eviction-interval-timer-in-ms: 4000
  client:
    #是否将自己注册到注册中心
    register-with-eureka: false
    #是否从eureka中获取注册信息
    fetch-registry: false
    #配置暴露给Client的请求地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/