server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    #是否将自己注册到注册中心
    register-with-eureka: false
    #是否从eureka中获取注册信息
    fetch-registry: false
    #配置暴露给Client的请求地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/